// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFOidhstLOR5_7VIf6Y57mJ1woIBXxYQ8',
    appId: '1:906649207599:web:4283500d67e810f8b657da',
    messagingSenderId: '906649207599',
    projectId: 'notify-46e77',
    authDomain: 'notify-46e77.firebaseapp.com',
    databaseURL: 'https://notify-46e77.firebaseio.com',
    storageBucket: 'notify-46e77.appspot.com',
    measurementId: 'G-2TJETTEF70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Qm9dxkHUq-AmsvINmw9996KjKgojUx8',
    appId: '1:906649207599:android:255b527f6a01c4f0b657da',
    messagingSenderId: '906649207599',
    projectId: 'notify-46e77',
    databaseURL: 'https://notify-46e77.firebaseio.com',
    storageBucket: 'notify-46e77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPutp7ystMt83WCj2gaD4hL5Zmnerqwjo',
    appId: '1:906649207599:ios:4777136d19cdab62b657da',
    messagingSenderId: '906649207599',
    projectId: 'notify-46e77',
    databaseURL: 'https://notify-46e77.firebaseio.com',
    storageBucket: 'notify-46e77.appspot.com',
    iosBundleId: 'com.example.meusEventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPutp7ystMt83WCj2gaD4hL5Zmnerqwjo',
    appId: '1:906649207599:ios:4777136d19cdab62b657da',
    messagingSenderId: '906649207599',
    projectId: 'notify-46e77',
    databaseURL: 'https://notify-46e77.firebaseio.com',
    storageBucket: 'notify-46e77.appspot.com',
    iosBundleId: 'com.example.meusEventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFOidhstLOR5_7VIf6Y57mJ1woIBXxYQ8',
    appId: '1:906649207599:web:073c1297a402ecd9b657da',
    messagingSenderId: '906649207599',
    projectId: 'notify-46e77',
    authDomain: 'notify-46e77.firebaseapp.com',
    databaseURL: 'https://notify-46e77.firebaseio.com',
    storageBucket: 'notify-46e77.appspot.com',
    measurementId: 'G-83J5BC86PH',
  );
}
